@api = http://localhost:4000/api

### Wine 1
POST {{api}}/wines
Content-Type: application/json

{
  "name": "El enemigo",
  "price": 20.5,
  "country": "Mendoza, Argentina",
  "region": "Lujan de Cuyo y Valle de Uco",
  "type": "red",
  "grape_type": ["Malbec"],
  "description": "Vino con cuerpo y aromas frutales",
  "stock": 20,
  "capacity": "750ml",
  "year": "2020",
  "images": ["image"]
}

### Wine 2
POST {{api}}/wines
Content-Type: application/json

{
  "name": "La Poderosa Cabernet Franc Merlot",
  "price": 18.2,
  "country": "Neuquen, Argentina",
  "region": "San Patricio del Chañar",
  "type": "red",
  "grape_type": ["Cabernet Franc", "Merlot"],
  "description": "En nariz premia con notas de pimiento asado al frente, acompañadas por un buen colchón de frutas rojas y negras. La madera hace su parte, con los característicos trazos de vainilla, tabaco y un sutil tostado.",
  "stock": 20,
  "capacity": "750ml",
  "year": "2019",
  "images": ["https://www.espaciovino.com.ar/media/default/0001/53/thumb_52733_default_big.jpeg"]
}

### Wine 3
POST {{api}}/wines
Content-Type: application/json

{
  "name": "Alamos Red Blend",
  "price": 14,
  "country": "Mendoza, Argentina",
  "region": "Lujan de Cuyo y Valle de Uco",
  "type": "red",
  "grape_type": ["Malbec", "Cabernet Franc", "Petit Verdot"],
  "description": "Es un vino exótico: frutado en rojo, bien intenso, y con un trazo expectorante que, una vez en el paladar, aporta delgadez y tensión.",
  "stock": 10,
  "capacity": "500ml",
  "year": "2017",
  "images": ["https://www.espaciovino.com.ar/media/default/0001/64/thumb_63693_default_big.jpeg"]
}

### Wine 4
POST {{api}}/wines
Content-Type: application/json

{
  "name": "El Abuelo Oporto",
  "price": 12,
  "country": "Mendoza, Argentina",
  "region": "Lujan de Cuyo y Valle de Uco",
  "type": "red",
  "grape_type": ["Oporto"],
  "description": "El Oporto se caracteriza por su gran intensidad aromática, la presencia del alcohol, su dulzura y la tonicidad en algunas de sus categorías.",
  "stock": 10,
  "capacity": "750ml",
  "year": "2021",
  "images": ["https://www.espaciovino.com.ar/media/default/0001/64/thumb_63809_default_big.jpeg"]
}

### Wine 5
POST {{api}}/wines
Content-Type: application/json

{
  "name": "Trumpeter Chardonnay",
  "price": 22,
  "country": "Mendoza, Argentina",
  "region": "Tupungato",
  "type": "white",
  "grape_type": ["Chardonnay"],
  "description": "Intenso color amarillo verdoso. Los primeros aromas que impactan en la nariz recuerdan a fruta madura de carozo (durazno) con un toque de vainilla, proveniente de la crianza en roble. Redondo y suave, en boca, entrega dejos a frutos tropicales (ananás) combinados con un fino marco mineral.",
  "stock": 20,
  "capacity": "750ml",
  "year": "2015",
  "images": ["https://www.espaciovino.com.ar/media/default/0001/62/thumb_61971_default_big.jpeg"]
}

### Wine 6
POST {{api}}/wines
Content-Type: application/json

{
  "name": "La Flor Malbec Rosé",
  "price": 18.6,
  "country": "Mendoza, Argentina",
  "region": "Alto Agrelo, Luján de Cuyo",
  "type": "rose",
  "grape_type": ["Malbec"],
  "description": "Nuestro Malbec Rosé posee un color tenue y brillante, su aroma es fresco y frutal de gran intensidad. Delicado al paladar, con expresiones que recuerdan a jalea de membrillos, típica de los Malbec de Alto Agrelo. Posee un final redondo, fresco y equilibrado.",
  "stock": 14,
  "capacity": "750ml",
  "year": "2019",
  "images": ["https://www.espaciovino.com.ar/media/default/0001/55/thumb_54222_default_big.jpeg"]
}

### Wine 7
POST {{api}}/wines
Content-Type: application/json

{
"name":"Salentein Single Vineyard Late Harvest",
"price":30.5,
"type":"white",
"stock":20,
"country":"Provincia de Mendoza",
"region":"Valle de Uco, Tunuyán",
"description":"A la vista, presenta un color dorado, límpido y brillante.En nariz, despliega complejos aromas que recuerdan a durazno, membrillo y cáscara de mandarina con sutiles notas de anís y flor de lima.",
"capacity":"750ml",
"grape_type":["Sauvignon Blanc"],
"year":"2019",
"images":["https://www.espaciovino.com.ar/media/default/0001/54/thumb_53622_default_big.jpeg"]
}

### Wine 8
POST {{api}}/wines
Content-Type: application/json

{
"name":"Nicasia Vineyards Red Blend Cabernet Franc",
"price": 18,
"type":"red",
"stock":15,
"country":"Provincia de Mendoza",
"region":"Altamira, San Carlos",
"description":"Se perciben en este vino elegantes notas herbáceas y de anís aportadas por el Cabernet Franc, junto a vivaces frutos negros y especias conferidos por el Merlot y el Petit Verdot.",
"capacity":"750ml",
"grape_type":["Cabernet Franc", "Merlot", "Petit Verdot"],
"year":"2021",
"images":["https://www.espaciovino.com.ar/media/default/0001/53/thumb_52946_default_big.jpeg"]
}

### Wine 9
POST {{api}}/wines
Content-Type: application/json

{
"name":"Nicasia Vineyards Blanc de Blancs",
"price": 15.5 ,
"type":"white",
"stock": 30,
"country":"Provincia de Mendoza",
"region":"Altamira, San Carlos",
"description":"Se perciben en este vino deliciosos sabores a frutos blancos y de durazno aportados por el Viognier, junto a delicadas notas florales típicas de la variedad Gewürztraminer y frescos dejos cítricos propios del Sauvignon Blanc.",
"capacity":"750ml",
"grape_type":["Viognier", " Gewürztraminer", "Sauvignon Blanc"],
"year":"2022",
"images":["https://www.espaciovino.com.ar/media/default/0001/53/thumb_52947_default_big.jpeg"]
}

### Wine 10
POST {{api}}/wines
Content-Type: application/json

{
"name":"Aimé Rosé",
"price":10.5 ,
"type":"rose",
"stock":10,
"country":"Provincia de Mendoza",
"region":"Lujan de Cuyo",
"description":"De color rosa salmón con tintes cobre, aromas frescos, con notas florales y frutos rojos",
"capacity":"750ml",
"grape_type":["Malbec"],
"year":"2019",
"images":["https://www.espaciovino.com.ar/media/default/0001/63/thumb_62352_default_big.jpeg"]
}

### Wine 11
POST {{api}}/wines
Content-Type: application/json

{
"name":"Portillo Rosé Malbec",
"price": 12 ,
"type":"rose",
"stock": 15,
"country":"Provincia de Mendoza",
"region":"Valle de Uco, Tunuyán",
"description":"Posee aromas florales que recuerdan a rosas y frutas rojas, como la cereza, frutilla y frambuesa",
"capacity":"750ml",
"grape_type":["Malbec"],
"year":"2020",
"images":["https://www.espaciovino.com.ar/media/default/0001/64/thumb_63975_default_big.jpeg"]
}

### Wine 12
POST {{api}}/wines
Content-Type: application/json

{
"name":"Pulenta Estate Rosé SIl Vous Plait",
"price":25 ,
"type":"rose",
"stock":14,
"country":"Provincia de Mendoza",
"region":"Agrelo, Luján de Cuyo",
"description":"De atractivo color rosa pétalo, muy elegante con brillantes reflejos. Posee gran expresión aromática que nos evoca a moras y guindas silvestres.",
"capacity":"750ml",
"grape_type":["Merlot"],
"year":"2021",
"images":["https://www.espaciovino.com.ar/media/default/0001/62/thumb_61840_default_big.jpeg"]
}

### Wine 13
POST {{api}}/wines
Content-Type: application/json

{
"name":"La Posta Rose Malbec",
"price": 13 ,
"type":"rose",
"stock": 16,
"country":"Provincia de Mendoza",
"region":"Valle de Uco ",
"description":"Flor de cerezo, granada, notas cítricas en nariz con una sensación en boca fresca y compleja.",
"capacity":"750ml",
"grape_type":["Malbec"],
"year":"2018",
"images":["https://www.espaciovino.com.ar/media/default/0001/62/thumb_61774_default_big.jpeg"]
}

### Wine 14
POST {{api}}/wines
Content-Type: application/json

{
"name":"Cobos Volturno",
"price": 105 ,
"type":"red",
"stock":3,
"country":"Provincia de Mendoza",
"region":"Perdriel, Luján de Cuyo",
"description":"Un elegante e intenso rojo desagrega en tonos violáceos, concentra aromas de frutos negros, moras maduras y arándanos, aromatizados con regaliz y chocolate.",
"capacity":"750ml",
"grape_type":["Blend"],
"year":"2015",
"images":["https://www.espaciovino.com.ar/media/default/0001/54/thumb_53445_default_big.jpeg"]
}

### Wine 15
POST {{api}}/wines
Content-Type: application/json

{
"name":"Zuccardi Finca Piedra Infinita Supercal",
"price": 95 ,
"type":"red",
"stock": 5,
"country":"Provincia de Mendoza",
"region":"Paraje Altamira, Valle de Uco",
"description":"Suelo aluvial supercalcáreo con piedras de gran tamaño cubiertas con carbonato de calcio que se encuentran en la superficie.",
"capacity":"750ml",
"grape_type":["Malbec"],
"year":"2016",
"images":["https://www.espaciovino.com.ar/media/default/0001/63/thumb_62982_default_big.jpeg"]
}

### Wine 16
POST {{api}}/wines
Content-Type: application/json

{
"name":"Catena Zapata Estiba Reservada",
"price": 80 ,
"type":"red",
"stock": 10,
"country":"Provincia de Mendoza",
"region":"La Pirámide, Agrelo",
"description":"Elegido el momento de la cosecha se seleccionan lotes en cada viñedo, luego se seleccionan plantas en cada lote elegido, luego los racimos que, una vez descobajados, terminan fermentando en pequeños barriles de roble francés, donde permanecen estacionados por aproximadamente 24 meses. Finalmente se seleccionan aquellos barriles que serán embotellados.",
"capacity":"750ml",
"grape_type":["Blend"],
"year":"2010",
"images":["https://www.espaciovino.com.ar/media/default/0001/54/thumb_53333_default_big.jpeg"]
}

### Wine 17
POST {{api}}/wines
Content-Type: application/json

{
"name":"Felipe Rutini Blend",
"price":78 ,
"type":"red",
"stock":6,
"country":"Provincia de Mendoza",
"region":"Agrelo",
"description":"Aroma muy intenso, a frutos rojos como ciruelas, cerezas, fresas y frutillas, acompañado con vainillas, chocolate y tabaco, que le brinda el roble nuevo.",
"capacity":"750ml",
"grape_type":["Cabernet Sauvignon", " Merlot", "Malbec"],
"year":"2013",
"images":["https://www.espaciovino.com.ar/media/default/0001/63/thumb_62032_default_big.jpeg"]
}

### Wine 18
POST {{api}}/wines
Content-Type: application/json

{
"name":"Piedra Líquida El Peral Sauvignon Blanc",
"price": 30 ,
"type":"white",
"stock": 5,
"country":"Provincia de Mendoza",
"region":"El Peral, Valle de Uco",
"description":"Esta variedad de uva necesita poco sol, el cuartel donde se encuentran estas vides está plantado con una irradiación no tan directa, con lo cual se ha logrado una maduración de la uva más lenta. Esto además ha permitido a la uva desarrollar una variedad de aromas más profundos, únicos.",
"capacity":"750ml",
"grape_type":["Sauvignon Blanc"],
"year":"2017",
"images":["https://www.espaciovino.com.ar/media/default/0001/68/thumb_67071_default_big.jpeg"]
}


### Wine 19
POST {{api}}/wines
Content-Type: application/json

{
"name":"Chacra Chardonnay",
"price": 50 ,
"type":"white",
"stock": 3,
"country":"Provincia de Rio Negro",
"region":"Mainque",
"description":"El vino es intenso y enérgico, de tono alto y vivo, redondo y austero, refinado y mineral. Tiene una sensación en boca seca y una salinidad natural en la zona.",
"capacity":"750ml",
"grape_type":["Chardonnay"],
"year":"2017",
"images":["https://www.espaciovino.com.ar/media/default/0001/64/thumb_63050_default_big.jpeg"]
}

### Wine 20
POST {{api}}/wines
Content-Type: application/json

{
"name":"Adrianna Chardonnay White",
"price": 45 ,
"type":"white",
"stock": 4,
"country":"Provincia de Mendoza",
"region":"Gualtallary, Tupungato, Valle de Uco",
"description":"Su aroma remite a vivaces notas cítricas y de frutos blancos de carozo.",
"capacity":"750ml",
"grape_type":["Chardonnay"],
"year":"2019",
"images":["https://www.espaciovino.com.ar/media/default/0001/68/thumb_67504_default_big.jpeg"]
}